### ISSUE TITLE
use private_key instead of key_file

### ISSUE THREAD

**Issue by davidoury** [data-fellas/dcos-up#12]
This connection: 
```
  connection {
    type = "ssh"
    user = "${lookup(var.provisioner,"username")}"
    private_key = "${file("keys/${lookup(var.provisioner,"key_name")}.pem")}"
    agent = false
  }
```
seemed to work, but this connection: 
```
  connection {
    user = "${lookup(var.provisioner,"username")}"
    key_file = "${path.module}/keys/${lookup(var.provisioner,"key_name")}.pem"
  }
```
did not and returned the error
```
* aws_spot_instance_request.dcos_master_node: unknown 'connection' argument "key_file"
```
until I replaced the line starting "key_file" with the line from the first connection starting "private_key". I am using Terraform v0.9.5.

**Comment by ishallbethat** [comment]
Hello i had the same problem.
using the "key_file" doesn't work when i'm provisioning aws instance.

**Comment by looppi** [comment]
I got the plan working with following tweaks: https://github.com/looppi/dcos-up/commit/4c99e9b6393233cb13a62b1b028f64ef0c908fd2 . I'm currently not 100% certain whether all of those are required.
