### ISSUE TITLE
Scale up

### ISSUE THREAD

**Issue by psuresh39** [data-fellas/dcos-up#13]
Got this working with latest terraform and latest stable DC/OS. I had to switch to use on demand instances vs spot instances and a few networking changes. Thanks a bunch for putting this out. 

What do you think is involved in being able to support adding agent nodes onto a running cluster ? autoscaling groups perhaps ? How can this project be extended ? I'm happy to contribute with some direction.

**Comment by psuresh39** [comment]
Actually got this working. Turns needed to tweak very little. terraform already handles only running the diff configs (which is only adding the new node). The consul watch then kicks in noticing that bootstrap node is running and installs dcos slave in it. super cool!

**Comment by frbayart** [comment]
Thank you, it's always a good news to know when it's working.
