### ISSUE TITLE
Trouble with consul

### ISSUE THREAD

**Issue by stroitelev** [data-fellas/dcos-up#6]
I found one trouble after starting script "dcos_install.sh" the consul was stopped. It is because dcos_install.sh do restart systemd-journald from the script. To fix this I recommended change one string in the consul.service in the provision script "setup-consul.sh":

from
Restart=on-failure
to 
Restart=always

I spent much time for debug this I hope it will help someone else ...

**Comment by frbayart** [comment]
Hi @stroitelev ,

be free to propose a Pull Request on it :)
