### ISSUE TITLE
Issue running with terraform v0.7.4

### ISSUE THREAD

**Issue by cwelton** [data-fellas/dcos-up#7]
I'm hitting the following issue, which I am currently suspecting is due to using a higher version of terraform:

```
bash$  terraform plan
Error loading config: Error loading /Users/cwelton/dcos-up/dcos.tf: Error reading config for aws_instance[dcos_bootstrap]: Invalid dot index found: 'var.provisioner.key_name'. Values in maps and lists can be referenced using square bracket indexing, like: 'var.mymap["key"]' or 'var.mylist[1]'. in:

${var.provisioner.key_name}
```

**Comment by subelsky** [comment]
I'm having the same trouble with other values. I tried a fix like this, which mostly worked:

```
  key_name = "${var.provisioner['key_name']}"
```

however even after I fix it I get: `Error loading config: Error loading .../dcos-up/dcos.tf: Error reading config for aws_instance[dcos_bootstrap]: parse error: syntax error`

**Comment by mudrii** [comment]
When you define variable don't use "." in the name
Ex 
Wrong: provisioner.key_name
Right: provisioner_key_name
